# - name: grab test-secret from azure kv
#   hosts: localhost
#   tasks:
#     - local_action:
#         command ansible-galaxy role install azure.azure_preview_modules

- name: grab test-secret from azure kv
  hosts: localhost
  gather_facts: false
  
  vars:
    kv_secret_name: "test"
  tasks:
    - name: set facts
      set_fact:
        az_vault_name: "kv-stage-medstack-pki"
        az_tenant_id:   '{{ lookup("env", "AZ_TENANT_ID") }}'
        az_client_id:   '{{ lookup("env", "AZ_CLIENT_ID") }}'
        az_client_secret:  '{{ lookup("env", "AZ_CLIENT_SECRET") }}'
        az_vault_url:      '{{ lookup("env", "AZ_VAULT_URL") }}'

    # - name: Set key vault secret fact
    #   set_fact: secretValue={{ lookup('azure_keyvault_secret',kv_secret_name,vault_url=az_vault_url, client_id=az_client_id, secret=az_client_secret, tenant_id=az_tenant_id) }}


    # - name: Get secret from Azure Key Vault
    #   azure.azcollection.azure_rm_keyvaultsecret:
    #     secret_name: "{{ kv_secret_name }}"
    #     keyvault_uri: "{{ lookup('env', 'AZ_VAULT_URL') }}"
    #     vault_uri: "{{ lookup('env', 'AZ_VAULT_URL') }}"
    #     client_id: "{{ lookup('env', 'AZ_CLIENT_ID') }}"
    #     client_secret: "{{ lookup('env', 'AZ_CLIENT_SECRET') }}"
    #     tenant: "{{ lookup('env', 'AZ_TENANT_ID') }}"
    #   register: secret_output
    - name: connect AZ CLI to Azure
      shell: |
        az login --service-principal -u "{{ az_client_id }}" -p "{{ az_client_secret }}" --tenant "{{ az_tenant_id }}"
      args:
        executable: /usr/bin/bash
    - name: Retrieve secret and register as var
      shell: az keyvault secret show --name "{{ kv_secret_name }}" --vault-name "{{ az_vault_name }}" --query value -o tsv
      args:
        executable: /usr/bin/bash
      register: azure_secret
    - debug:
        msg: "{{ azure_secret.stdout }}"
    - name: Output key vault secret
      debug:
        msg: "{{ secretValue }}"