
- name: grab test-secret from azure kv
  hosts: localhost
  gather_facts: false
  collections:
    - azure.azcollection
  vars:
    kv_cacertificate_name: "{{ cacertificate }}"
    kv_caprivatekey_name: "{{ caprivatekey }}"

  tasks:
  #Set azure key vault access credential in AWX instance
    - name: set facts
      set_fact:
        az_vault_name: "kv-stage-medstack-pki"
        az_tenant_id:   '{{ lookup("env", "AZ_TENANT_ID") }}'
        az_client_id:   '{{ lookup("env", "AZ_CLIENT_ID") }}'
        az_client_secret:  '{{ lookup("env", "AZ_CLIENT_SECRET") }}'
        az_vault_url:      '{{ lookup("env", "AZ_VAULT_URL") }}'
        subscription_id: '{{ lookup("env", "AZ_SUBSCRIPTION_ID") }}'
        
  # Get CACertificate
    - name: Get latest version of specific CACertificate for cluster
      azure_rm_keyvaultsecret_info:
        vault_uri: "https://{{ az_vault_name }}.vault.azure.net"
        client_id: '{{ az_client_id }}'
        secret: '{{ az_client_secret }}'
        tenant: '{{ az_tenant_id }}'
        subscription_id: '{{ subscription_id }}'
        name: kv_cacertificate_name
      register: cacert_output
  #Get CAPrivateKey
    - name: Get latest version of specific CAPrivateKey for Cluster
      azure_rm_keyvaultsecret_info:
        vault_uri: "https://{{ az_vault_name }}.vault.azure.net"
        client_id: '{{ az_client_id }}'
        secret: '{{ az_client_secret }}'
        tenant: '{{ az_tenant_id }}'
        subscription_id: '{{ subscription_id }}'
        name: kv_caprivatekey_name
      register: cakey_output

  #Create Directory
    - name: Create directory for certificates on remote
      file:
        path: "/tmp/ansible/certificate"
        state: directory
        mode: '0755'

  #write Certificate into a file
    - name: Write the CA certificate to a file
      ansible.builtin.copy:
        content: "{{ cacert_output.secrets[0].secret }}"
        dest: "/tmp/ansible/certificate/CACertificate.pem"
        mode: '0600'

  #write CAPrivateKey into a file
    - name: Write the CAPrivateKey to a file
      ansible.builtin.copy:
        content: "{{ cakey_output.secrets[0].secret }}"
        dest: "/tmp/ansible/certificate/CAPrivateKey.pem"
        mode: '0600'
      
  # Test Step: To check whether secrets can be pulled properly 
    - name: Display the secret
      debug:
        msg: "{{ secret_output.secrets[0].secret }}"
    