
- name: grab test-secret from azure kv
  hosts: localhost
  gather_facts: false
  collections:
    - azure.azcollection
  vars:
    kv_secret_name: "test"

  tasks:
    - name: set facts
      set_fact:
        az_vault_name: "kv-stage-medstack-pki"
        az_tenant_id:   '{{ lookup("env", "AZ_TENANT_ID") }}'
        az_client_id:   '{{ lookup("env", "AZ_CLIENT_ID") }}'
        az_client_secret:  '{{ lookup("env", "AZ_CLIENT_SECRET") }}'
        az_vault_url:      '{{ lookup("env", "AZ_VAULT_URL") }}'
    # - name: Set Azure authentication facts
    #   ansible.builtin.set_fact:
    #     ansible_azure_auth:
    #       client_id: '{{ lookup("env", "AZ_CLIENT_ID") }}'
    #       secret: '{{ lookup("env", "AZ_CLIENT_SECRET") }}'
    #       tenant: '{{ lookup("env", "AZ_TENANT_ID") }}'
    #       subscription_id: '{{ lookup("env", "AZ_SUBSCRIPTION_ID") }}'
    - name: Get latest version of specific secret
      azure_rm_keyvaultsecret_info:
        vault_uri: "https://{{ az_vault_name }}.vault.azure.net"
        client_id: '{{ lookup("env", "AZ_CLIENT_ID") }}'
        secret: '{{ lookup("env", "AZ_CLIENT_SECRET") }}'
        tenant: '{{ lookup("env", "AZ_TENANT_ID") }}'
        subscription_id: '{{ lookup("env", "AZ_SUBSCRIPTION_ID") }}'
        name: test
      register: secret_output
    - name: Write the certificate to a file
      ansible.builtin.copy:
        content: "{{ secret_output.secrets[0].secret }}"
        dest: "/tmp/ansible/certificate/ca_server_certificate.crt"
        mode: '0600'
    - name: Display the secret
      debug:
        msg: "{{ secret_output.secrets[0].secret }}"
    